spring:
  application:
    name: SingSongSangSong
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
        domain: singsongsangsong.com
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 813928593657-9v2bpcp9p2l3i3j5ri6vrdnu0dd1sif5.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: https://api.singsongsangsong.com/login/oauth2/code/google
          naver:
            client-id: t8m3plQmDMt1BM58c5g6
            client-secret: VbWntwUdPR
            redirect-uri: http://api.singsongsangsong.com/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
          kakao:
            client-id: d3ace32d6368823829feba818d7ff6d3
            client-secret: LF49xe2E8pAoMeQaRtskgi5hIvzX4CbK
            redirect-uri: http://api.singsongsangsong.com/login/oauth2/code/kakao
            scope:
              - account_email
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
    singsongsangsong:
      #      redirect-uri: http://localhost:3000/
      # TODO : url temp용으로 localhost
      redirect-uri: https://www.singsongsangsong.com/

  sql:
    init:
      mode: always
  
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P22E206?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S10P22E206
    password: CuSfPXDNXr
  data:
    mongodb:
      uri: mongodb+srv://S10P22E206:rui4ZhwEt1@ssafy.ngivl.mongodb.net/S10P22E206?authSource=admin

  output:
    ansi:
      enabled: always
  batch:
    jdbc:
      initialize-schema: always

jwt:
  secretKey: "QjaVCjBnUIWtzWt8erZbO2ZFApswkbVhSArPu6GshQ8jp2OLtRhhOVl3pv8DTxaBA6kEjeZPJz8Uhy66tpGVwBEWIdflSQcSwTNvnMM7FSL8hz8N4syBT9nWqT006unUVqIemV9L8jMtu2bPFRu8p6qO8RXySni4cliOF4Wd1dUWiAx7Io4ONcW3UHXwtD4QvDstZm4EWHGnXXaZ4um4Pj5BXwJJb7jmlGMXYM84ZBwyDA6I1XmpQlv19O0bnZjqMqbNo5ockscMYv1xOHQSiTXBf6YjD0y98ZgRZiRkz4cYjxvJDpWGN28DmArr2TZ0AvRLd78uvmJzybH137CIgGRzwtfR91MbG5Q3QAMytYPgdkxv2weeOFGcAlIUEIAXkn6pXRPrxWZBUL3NrzEyYJyK6xUbZM1T4ZgelQ650DK6RAdWgLaHA0sdw7lZltcZRoVjhgteMWpnvPWOaZ97xR25cNYdOLvFhrO9bev8QnZfHB7HKiPE3gCpN4539wNlQjaVCjBnUIWtzWt8erZbO2ZFApswkbVhSArPu6GshQ8jp2OLtRhhOVl3pv8DTxaBA6kEjeZPJz8Uhy66tpGVwBEWIdflSQcSwTNvnMM7FSL8hz8N4syBT9nWqT006unUVqIemV9L8jMtu2bPFRu8p6qO8RXySni4cliOF4Wd1dUWiAx7Io4ONcW3UHXwtD4QvDstZm4EWHGnXXaZ4um4Pj5BXwJJb7jmlGMXYM84ZBwyDA6I1XmpQlv19O0bnZjqMqbNo5ockscMYv1xOHQSiTXBf6YjD0y98ZgRZiRkz4cYjxvJDpWGN28DmArr2TZ0AvRLd78uvmJzybH137CIgGRzwtfR91MbG5Q3QAMytYPgdkxv2weeOFGcAlIUEIAXkn6pXRPrxWZBUL3NrzEyYJyK6xUbZM1T4ZgelQ650DK6RAdWgLaHA0sdw7lZltcZRoVjhgteMWpnvPWOaZ97xR25cNYdOLvFhrO9bev8QnZfHB7HKiPE3gCpN4539wNl"

  access:
    expiration: 3600000 # 1??(60?) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

synology:
  host: zip.udon.party
  account: jinjoo021
  passwd: 206s4nas!
  baseDir: /ssafy

minio:
  endpoint: http://zip.udon.party:40001
  accessKey: mtppqpRtSxArNq81phwB
  secretKey: pqjrczK0C5JsFDnociyril8CqCbB5Mtfybkhl8p5
  serviceName: s3

csv:
  file:
    dir:
      "./csv/"

logging:
  level:
    org:
      springframework:
        mvc: TRACE
        test:
          context:
            cache: DEBUG

webclient:
  baseUrl: https://dsp.singsongsangsong.com
  contentType: application/json
